### PR TITLE
Co-exist with phonegap-plugin-push

### PR DESCRIPTION
**Pull request by midhunanew**
`Error: Permission name C2D_MESSAGE is not unique` while cordova build

### CODE REVIEW

**Comment by taivo** [comment]
Thanks @midhunanew . You just taught me something about the ${applicationId} variable.

Are you using phonegap-plugin-push to get notifications on Windows?

**Comment by midhunanew** [comment]
@taivo You are welcome. :) 
I'm not using `phonegap-plugin-push` on Windows. I'm currently working on Android and iOS.

**Comment by taivo** [comment]
I'm curious: what is the need to use both push plugins together?

**Comment by midhunanew** [comment]
@taivo Actually I'm working on a maintenance project, I guess they were using 'phonegap-plugin-push' for register/unregister callbacks.

**Pull request merged**
