### PR TITLE
correção push notification android oreo (create channel)

### PR DESCRIPTION
**Pull request by Jsmn14**
Push Notifications using channel (Andoid oreo - SDK 26)

### CODE REVIEW

**Comment by fmendoza** [comment]
Is this working on both background in foreground? In my tests it only works when the app is opened in foreground

**Comment by Jsmn14** [comment]
> Is this working on both background in foreground? In my tests it only works when the app is opened in foreground

It works for me. Please, change target sdk 26 in config xml and try again.

**Comment by fmendoza** [comment]
yes it works :-)

**Comment by taivo** [comment]
Thanks for the PR @Jsmn14 and @fmendoza for the test usage. 👍

**Pull request merged**
